# Generated by Django 5.1.1 on 2024-10-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_achievement_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.AddField(
            model_name='customuser',
            name='stats_rps_lose',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stats_rps_win',
            field=models.IntegerField(default=0),
        ),
    ]
