# Generated by Django 5.1.1 on 2024-11-02 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_achievement_delete_stat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=6, validators=[django.core.validators.RegexValidator(message='请输入合法的十六进制六位数(使用大写字母)', regex='^[#]{1}[A-F0-9]{6}$')]),
        ),
    ]
