# Generated by Django 5.1.1 on 2024-11-03 02:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=6, validators=[django.core.validators.RegexValidator(message='请输入合法的十六进制六位数', regex='^[#]{1}[A-F0-9a-f]{6}$')]),
        ),
    ]
