# Generated by Django 5.1.1 on 2024-11-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
